listener 8883
cafile /home/votre_user/cyber-digital-twin/certs/ca.crt
certfile /home/votre_user/cyber-digital-twin/certs/server.crt
keyfile /home/votre_user/cyber-digital-twin/certs/server.key
tls_version tlsv1.2