"""Unit tests for backend.events.normalizer.EventNormalizer.

Coverage matrix (23 required cases + supplementary sub-cases)
--------------------------------------------------------------
 1. MQTT IoT normal (temperature — grue_G01)
 2. MQTT temperature
 3. MQTT humidity
 4. MQTT vibration
 5. MQTT smoke
 6. MQTT presence  — status is bool
 7. MQTT camera    — people_count + unknown fields in metadata
 8. MQTT GPS       — latitude / longitude
 9. Drone telemetry (type=drone)
10. Drone event    (type=drone_event)
11. HTTP telemetry
12. UDP telemetry
13. Timestamp absent → generated by normalizer
14. device_id absent → fallback to "unknown"
15. Unknown / unexpected type → IOT_TELEMETRY default
16. Exact conservation of raw_payload
17. Conservation of mqtt_topic
18. Conservation of token
19. IP/MAC simulated → observed=False, simulated=True
20. Absence of destination_port
21. Absence of latency
22. Absence of throughput
23. Absence of all invented network metrics

Design notes
------------
- No DB, no filesystem, no network, no FastAPI, no MQTT broker.
- Only backend.events.* is imported from the project; no backend.main.
- Each test method is self-contained: no shared mutable state.
- Parametrised cases use subTest for clear failure attribution.
"""
from __future__ import annotations

import time
import unittest

from backend.events.contracts import EventKind, Transport
from backend.events.normalizer import EventNormalizer

# ---------------------------------------------------------------------------
# Convenience shorthand
# ---------------------------------------------------------------------------

def _n(payload: dict, transport=Transport.MQTT):
    """Shorthand: EventNormalizer.normalize(payload, transport)."""
    return EventNormalizer.normalize(payload, transport)


# ---------------------------------------------------------------------------
# Shared payload factories (never mutated between tests)
# ---------------------------------------------------------------------------

def _iot_payload(device_id="grue_G01", dev_type="temperature", **extra) -> dict:
    base = {
        "device_id": device_id,
        "type": dev_type,
        "value": 28.3,
        "unit": "°C",
        "timestamp": 1_700_000_000.0,
        "token": "tk_temp123",
        "mqtt_topic": "port/gantry_crane/temperature",
        "ip_src": "192.168.1.10",
        "mac_src": "AA:BB:CC:DD:EE:01",
        "port_src": 1883,
    }
    base.update(extra)
    return base


def _drone_telemetry_payload(**extra) -> dict:
    base = {
        "device_id": "drone_01",
        "type": "drone",
        "x": 3.0,
        "y": 2.0,
        "altitude": 10.0,
        "battery": 85.5,
        "status": "flying",
        "mission_id": "m-001",
        "mission_status": "active",
        "timestamp": 1_700_000_007.0,
        "token": "tk_drone_secure_001",
        "mqtt_topic": "drone/telemetry",
        "ip_src": "192.168.1.101",
        "mac_src": "AA:BB:CC:DD:EE:11",
        "port_src": 1883,
    }
    base.update(extra)
    return base


def _drone_event_payload(**extra) -> dict:
    base = {
        "device_id": "drone_01",
        "type": "drone_event",
        "event_type": "mission_started",
        "mission_id": "m-001",
        "timestamp": 1_700_000_010.0,
        "token": "tk_drone_secure_001",
        "mqtt_topic": "drone/event",
    }
    base.update(extra)
    return base


# ===========================================================================
# TEST 1 — MQTT IoT normal (temperature, full payload)
# ===========================================================================

class Test01MqttIoTNormal(unittest.TestCase):
    """Case 1: full real-world MQTT temperature payload from grue_G01."""

    def setUp(self):
        self.p = _iot_payload()
        self.e = _n(self.p)

    def test_event_kind_is_iot_telemetry(self):
        self.assertEqual(self.e.event_kind, EventKind.IOT_TELEMETRY)

    def test_transport_is_mqtt(self):
        self.assertEqual(self.e.transport, Transport.MQTT)

    def test_occurred_at_preserved(self):
        self.assertEqual(self.e.occurred_at, 1_700_000_000.0)

    def test_device_id(self):
        self.assertEqual(self.e.device.device_id, "grue_G01")

    def test_device_type(self):
        self.assertEqual(self.e.device.device_type, "temperature")

    def test_data_value(self):
        self.assertEqual(self.e.data.value, 28.3)

    def test_data_unit(self):
        self.assertEqual(self.e.data.unit, "°C")

    def test_identity_token(self):
        self.assertEqual(self.e.identity.token, "tk_temp123")

    def test_identity_mqtt_topic(self):
        self.assertEqual(self.e.identity.mqtt_topic, "port/gantry_crane/temperature")

    def test_network_ip_src(self):
        self.assertEqual(self.e.network.ip_src, "192.168.1.10")

    def test_network_mac_src(self):
        self.assertEqual(self.e.network.mac_src, "AA:BB:CC:DD:EE:01")

    def test_network_source_port(self):
        self.assertEqual(self.e.network.source_port, 1883)

    def test_network_observed_false(self):
        self.assertIs(self.e.network.observed, False)

    def test_network_simulated_true(self):
        self.assertIs(self.e.network.simulated, True)

    def test_event_id_is_uuid4(self):
        self.assertEqual(len(self.e.event_id), 36)
        self.assertIn("-", self.e.event_id)


# ===========================================================================
# TEST 2 — MQTT temperature
# ===========================================================================

class Test02MqttTemperature(unittest.TestCase):
    """Case 2: temperature sensor classification and value extraction."""

    def test_temperature_classified_as_iot(self):
        e = _n({"device_id": "grue_G01", "type": "temperature",
                "value": 35.1, "unit": "°C", "timestamp": 1.0})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertEqual(e.data.value, 35.1)
        self.assertEqual(e.data.unit, "°C")


# ===========================================================================
# TEST 3 — MQTT humidity
# ===========================================================================

class Test03MqttHumidity(unittest.TestCase):
    """Case 3: humidity sensor."""

    def test_humidity_classified_as_iot(self):
        e = _n({"device_id": "station_H01", "type": "humidity",
                "value": 62.5, "unit": "%", "timestamp": 2.0,
                "ip_src": "192.168.1.11", "mac_src": "AA:BB:CC:DD:EE:02", "port_src": 1883})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertEqual(e.device.device_type, "humidity")
        self.assertEqual(e.data.value, 62.5)
        self.assertEqual(e.data.unit, "%")


# ===========================================================================
# TEST 4 — MQTT vibration
# ===========================================================================

class Test04MqttVibration(unittest.TestCase):
    """Case 4: vibration sensor."""

    def test_vibration_classified_as_iot(self):
        e = _n({"device_id": "portique_P01", "type": "vibration",
                "value": 0.3, "unit": "g", "timestamp": 3.0})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertEqual(e.data.value, 0.3)
        self.assertEqual(e.data.unit, "g")


# ===========================================================================
# TEST 5 — MQTT smoke
# ===========================================================================

class Test05MqttSmoke(unittest.TestCase):
    """Case 5: smoke detector."""

    def test_smoke_classified_as_iot(self):
        e = _n({"device_id": "entrepot_E01", "type": "smoke",
                "value": 0.5, "unit": "ppm", "timestamp": 4.0})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertEqual(e.data.value, 0.5)
        self.assertEqual(e.data.unit, "ppm")


# ===========================================================================
# TEST 6 — MQTT presence — status is bool
# ===========================================================================

class Test06MqttPresenceBoolStatus(unittest.TestCase):
    """Case 6: presence sensor publishes status as Python bool; must not be cast."""

    def setUp(self):
        self.p_true  = {"device_id": "parking_P01", "type": "presence",
                        "status": True,  "timestamp": 5.0, "token": "tk_pres444",
                        "mqtt_topic": "port/parking/presence",
                        "ip_src": "192.168.1.60", "mac_src": "AA:BB:CC:DD:EE:08", "port_src": 1883}
        self.p_false = dict(self.p_true, status=False)

    def test_status_true_is_bool(self):
        e = _n(self.p_true)
        self.assertIs(e.data.status, True)
        self.assertIs(type(e.data.status), bool)

    def test_status_false_is_bool(self):
        e = _n(self.p_false)
        self.assertIs(e.data.status, False)
        self.assertIs(type(e.data.status), bool)

    def test_event_kind(self):
        e = _n(self.p_true)
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)


# ===========================================================================
# TEST 7 — MQTT camera — people_count + unknown fields in metadata
# ===========================================================================

class Test07MqttCamera(unittest.TestCase):
    """Case 7: camera sensor with optional event/confidence extra fields."""

    def setUp(self):
        self.p = {
            "device_id": "camera_Q01", "type": "camera",
            "people_count": 5, "timestamp": 6.0, "token": "tk_cam000",
            "mqtt_topic": "port/quay/camera",
            "ip_src": "192.168.1.20", "mac_src": "AA:BB:CC:DD:EE:04", "port_src": 1883,
            "event": "intrusion", "confidence": 0.92,
        }
        self.e = _n(self.p)

    def test_event_kind(self):
        self.assertEqual(self.e.event_kind, EventKind.IOT_TELEMETRY)

    def test_people_count(self):
        self.assertEqual(self.e.data.people_count, 5)

    def test_event_in_metadata(self):
        self.assertEqual(self.e.metadata.get("event"), "intrusion")

    def test_confidence_in_metadata(self):
        self.assertAlmostEqual(self.e.metadata.get("confidence"), 0.92)

    def test_value_is_none(self):
        self.assertIsNone(self.e.data.value)


# ===========================================================================
# TEST 8 — MQTT GPS
# ===========================================================================

class Test08MqttGPS(unittest.TestCase):
    """Case 8: GPS container sensor — latitude / longitude extraction."""

    def test_gps_fields(self):
        e = _n({"device_id": "camion_C12", "type": "gps",
                "latitude": 35.767, "longitude": -5.800, "timestamp": 7.0,
                "ip_src": "192.168.1.30", "mac_src": "AA:BB:CC:DD:EE:05", "port_src": 1883})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertAlmostEqual(e.data.latitude,   35.767)
        self.assertAlmostEqual(e.data.longitude, -5.800)
        self.assertIsNone(e.data.value)


# ===========================================================================
# TEST 9 — Drone telemetry
# ===========================================================================

class Test09DroneTelemetry(unittest.TestCase):
    """Case 9: drone telemetry — classification via type and via topic."""

    def test_type_drone_classified(self):
        e = _n(_drone_telemetry_payload())
        self.assertEqual(e.event_kind, EventKind.DRONE_TELEMETRY)

    def test_type_drone_gps_classified(self):
        e = _n({"device_id": "drone_01", "type": "drone_gps",
                "latitude": 2.0, "longitude": 3.0, "altitude": 5.0,
                "timestamp": 8.0, "mqtt_topic": "drone/gps"})
        self.assertEqual(e.event_kind, EventKind.DRONE_TELEMETRY)

    def test_type_camera_stream_classified(self):
        e = _n({"device_id": "drone_01", "type": "camera_stream",
                "stream_id": "drone_01_camera", "active": True,
                "timestamp": 9.0, "mqtt_topic": "drone/camera"})
        self.assertEqual(e.event_kind, EventKind.DRONE_TELEMETRY)

    def test_topic_drone_telemetry_classifies_when_type_empty(self):
        # Verify topic-based classification works independently of type
        e = _n({"device_id": "drone_01", "type": "drone",
                "timestamp": 10.0, "mqtt_topic": "drone/telemetry"})
        self.assertEqual(e.event_kind, EventKind.DRONE_TELEMETRY)

    def test_drone_extra_fields_in_metadata(self):
        e = _n(_drone_telemetry_payload())
        for key in ("x", "y", "altitude", "battery", "mission_id", "mission_status"):
            with self.subTest(field=key):
                self.assertIn(key, e.metadata)

    def test_drone_status_type_preserved(self):
        e = _n(_drone_telemetry_payload())
        self.assertEqual(e.data.status, "flying")
        self.assertIs(type(e.data.status), str)

    def test_drone_not_iot(self):
        e = _n(_drone_telemetry_payload())
        self.assertNotEqual(e.event_kind, EventKind.IOT_TELEMETRY)


# ===========================================================================
# TEST 10 — Drone event
# ===========================================================================

class Test10DroneEvent(unittest.TestCase):
    """Case 10: drone_event type or drone/event topic → DRONE_EVENT."""

    def test_type_drone_event_classified(self):
        e = _n(_drone_event_payload())
        self.assertEqual(e.event_kind, EventKind.DRONE_EVENT)

    def test_topic_drone_event_classified(self):
        # type intentionally empty, only topic drives classification
        e = _n({"device_id": "drone_01", "type": "",
                "timestamp": 11.0, "mqtt_topic": "drone/event"})
        self.assertEqual(e.event_kind, EventKind.DRONE_EVENT)

    def test_event_type_in_metadata(self):
        e = _n(_drone_event_payload())
        self.assertEqual(e.metadata.get("event_type"), "mission_started")

    def test_mission_id_in_metadata(self):
        e = _n(_drone_event_payload())
        self.assertEqual(e.metadata.get("mission_id"), "m-001")

    def test_not_iot_not_drone_telemetry(self):
        e = _n(_drone_event_payload())
        self.assertNotEqual(e.event_kind, EventKind.IOT_TELEMETRY)
        self.assertNotEqual(e.event_kind, EventKind.DRONE_TELEMETRY)


# ===========================================================================
# TEST 11 — HTTP telemetry
# ===========================================================================

class Test11HttpTelemetry(unittest.TestCase):
    """Case 11: HTTP ingress — transport enum, no mqtt_topic."""

    def setUp(self):
        self.p = {"device_id": "temp_01", "type": "temperature",
                  "value": 22.0, "unit": "°C", "timestamp": 12.0,
                  "token": "tk_temp123",
                  "ip_src": "10.0.0.1", "mac_src": "BB:CC:DD:EE:FF:01"}
        self.e = _n(self.p, Transport.HTTP)

    def test_transport_http(self):
        self.assertEqual(self.e.transport, Transport.HTTP)

    def test_event_kind_iot(self):
        self.assertEqual(self.e.event_kind, EventKind.IOT_TELEMETRY)

    def test_no_mqtt_topic(self):
        self.assertIsNone(self.e.identity.mqtt_topic)

    def test_value(self):
        self.assertEqual(self.e.data.value, 22.0)

    def test_transport_accepted_as_string(self):
        e = _n(self.p, "http")
        self.assertEqual(e.transport, Transport.HTTP)


# ===========================================================================
# TEST 12 — UDP telemetry
# ===========================================================================

class Test12UdpTelemetry(unittest.TestCase):
    """Case 12: UDP ingress — transport string "udp" accepted."""

    def test_udp_transport_enum(self):
        e = _n({"device_id": "hum_01", "type": "humidity",
                "value": 55.0, "unit": "%", "timestamp": 13.0}, "udp")
        self.assertEqual(e.transport, Transport.UDP)

    def test_udp_event_kind(self):
        e = _n({"device_id": "hum_01", "type": "humidity",
                "value": 55.0, "timestamp": 13.0}, Transport.UDP)
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)

    def test_udp_no_mqtt_topic(self):
        e = _n({"device_id": "hum_01", "type": "humidity",
                "timestamp": 13.0}, Transport.UDP)
        self.assertIsNone(e.identity.mqtt_topic)


# ===========================================================================
# TEST 13 — Timestamp absent
# ===========================================================================

class Test13TimestampAbsent(unittest.TestCase):
    """Case 13: when timestamp is missing the normalizer generates one."""

    def test_occurred_at_generated(self):
        before = time.time()
        e = _n({"device_id": "gate_01", "type": "barrier", "status": "closed"})
        after  = time.time()
        self.assertGreaterEqual(e.occurred_at, before)
        self.assertLessEqual(e.occurred_at, after)

    def test_two_calls_get_different_timestamps(self):
        p = {"device_id": "gate_01", "type": "barrier"}
        e1 = _n(p)
        time.sleep(0.01)
        e2 = _n(p)
        self.assertLessEqual(e1.occurred_at, e2.occurred_at)


# ===========================================================================
# TEST 14 — device_id absent
# ===========================================================================

class Test14DeviceIdAbsent(unittest.TestCase):
    """Case 14: missing device_id falls back to "unknown"."""

    def test_fallback_to_unknown(self):
        e = _n({"type": "temperature", "value": 30.0, "timestamp": 14.0})
        self.assertEqual(e.device.device_id, "unknown")

    def test_none_device_id_also_falls_back(self):
        e = _n({"device_id": None, "type": "temperature", "timestamp": 14.0})
        self.assertEqual(e.device.device_id, "unknown")

    def test_empty_string_device_id_falls_back(self):
        e = _n({"device_id": "", "type": "temperature", "timestamp": 14.0})
        self.assertEqual(e.device.device_id, "unknown")


# ===========================================================================
# TEST 15 — Unknown / unexpected device type
# ===========================================================================

class Test15UnknownType(unittest.TestCase):
    """Case 15: unknown type → IOT_TELEMETRY default, device_type preserved."""

    def test_unknown_type_classifies_as_iot(self):
        e = _n({"device_id": "mystery_01", "type": "unknown_sensor",
                "value": 99.9, "timestamp": 15.0})
        self.assertEqual(e.event_kind, EventKind.IOT_TELEMETRY)

    def test_unknown_type_preserved_in_device_type(self):
        e = _n({"device_id": "x", "type": "alien_signal", "timestamp": 15.0})
        self.assertEqual(e.device.device_type, "alien_signal")

    def test_empty_type_gives_none_device_type(self):
        e = _n({"device_id": "x", "type": "", "timestamp": 15.0})
        self.assertIsNone(e.device.device_type)


# ===========================================================================
# TEST 16 — Exact conservation of raw_payload
# ===========================================================================

class Test16RawPayloadConservation(unittest.TestCase):
    """Case 16: raw_payload is an exact shallow copy, independent of the original."""

    def test_raw_payload_equals_original(self):
        p = _iot_payload()
        original_copy = dict(p)
        e = _n(p)
        self.assertEqual(e.raw_payload, original_copy)

    def test_raw_payload_is_a_copy_not_alias(self):
        p = _iot_payload()
        e = _n(p)
        self.assertIsNot(e.raw_payload, p)

    def test_mutating_original_does_not_affect_raw_payload(self):
        p = _iot_payload()
        e = _n(p)
        p["value"] = 999.0
        self.assertNotEqual(e.raw_payload.get("value"), 999.0)

    def test_mutating_raw_payload_does_not_affect_caller(self):
        p = _iot_payload()
        e = _n(p)
        e.raw_payload["value"] = 0.0
        # Original dict must be unchanged
        self.assertEqual(p["value"], 28.3)

    def test_extra_fields_present_in_raw_payload(self):
        p = _iot_payload(future_field="xyz")
        e = _n(p)
        self.assertEqual(e.raw_payload.get("future_field"), "xyz")


# ===========================================================================
# TEST 17 — Conservation of mqtt_topic
# ===========================================================================

class Test17MqttTopicConservation(unittest.TestCase):
    """Case 17: mqtt_topic is preserved in identity.mqtt_topic."""

    def test_topic_preserved(self):
        p = _iot_payload(mqtt_topic="port/camera01/status", device_id="cam_01",
                         dev_type="camera")
        e = _n({**p, "type": "camera"})
        self.assertEqual(e.identity.mqtt_topic, "port/camera01/status")

    def test_legacy_topic_preserved(self):
        e = _n({"device_id": "temp_01", "type": "temperature",
                "mqtt_topic": "port/container01/temperature", "timestamp": 17.0})
        self.assertEqual(e.identity.mqtt_topic, "port/container01/temperature")

    def test_no_topic_gives_none(self):
        e = _n({"device_id": "temp_01", "type": "temperature", "timestamp": 17.0})
        self.assertIsNone(e.identity.mqtt_topic)


# ===========================================================================
# TEST 18 — Conservation of token
# ===========================================================================

class Test18TokenConservation(unittest.TestCase):
    """Case 18: token is preserved in identity.token for all transports."""

    def test_token_mqtt(self):
        e = _n({"device_id": "cam_01", "type": "camera",
                "token": "tk_cam000", "timestamp": 18.0}, Transport.MQTT)
        self.assertEqual(e.identity.token, "tk_cam000")

    def test_token_http(self):
        e = _n({"device_id": "temp_01", "type": "temperature",
                "token": "tk_temp123", "timestamp": 18.0}, Transport.HTTP)
        self.assertEqual(e.identity.token, "tk_temp123")

    def test_token_udp(self):
        e = _n({"device_id": "hum_01", "type": "humidity",
                "token": "tk_hum456", "timestamp": 18.0}, Transport.UDP)
        self.assertEqual(e.identity.token, "tk_hum456")

    def test_absent_token_gives_none(self):
        e = _n({"device_id": "x", "type": "temperature", "timestamp": 18.0})
        self.assertIsNone(e.identity.token)


# ===========================================================================
# TEST 19 — IP/MAC simulated → observed=False, simulated=True
# ===========================================================================

class Test19SimulatedNetworkMetadata(unittest.TestCase):
    """Case 19: simulator IP/MAC are metadata, never a real network capture."""

    def setUp(self):
        self.e = _n({
            "device_id": "portique_P01", "type": "vibration", "value": 0.2,
            "timestamp": 19.0,
            "ip_src": "192.168.1.12", "mac_src": "AA:BB:CC:DD:EE:03", "port_src": 1883,
        })

    def test_ip_src_extracted(self):
        self.assertEqual(self.e.network.ip_src, "192.168.1.12")

    def test_mac_src_extracted(self):
        self.assertEqual(self.e.network.mac_src, "AA:BB:CC:DD:EE:03")

    def test_source_port_extracted(self):
        self.assertEqual(self.e.network.source_port, 1883)

    def test_observed_always_false(self):
        self.assertIs(self.e.network.observed, False)

    def test_simulated_always_true(self):
        self.assertIs(self.e.network.simulated, True)

    def test_observed_false_even_with_real_looking_ip(self):
        # Even if an IP looks real, the normalizer must never set observed=True
        e = _n({"device_id": "x", "type": "t", "timestamp": 19.0,
                "ip_src": "8.8.8.8", "mac_src": "FF:FF:FF:FF:FF:FF"})
        self.assertIs(e.network.observed, False)
        self.assertIs(e.network.simulated, True)


# ===========================================================================
# TEST 20 — Absence of destination_port
# ===========================================================================

class Test20NoDestinationPort(unittest.TestCase):
    """Case 20: destination_port must never be populated by the normalizer."""

    def test_destination_port_none(self):
        e = _n(_iot_payload())
        self.assertIsNone(e.network.destination_port)

    def test_destination_port_none_even_if_in_payload(self):
        # destination_port is not in _CONSUMED_KEYS, so it lands in metadata
        p = _iot_payload()
        p["destination_port"] = 8883
        e = _n(p)
        self.assertIsNone(e.network.destination_port)
        self.assertEqual(e.metadata.get("destination_port"), 8883)


# ===========================================================================
# TEST 21 — Absence of latency
# ===========================================================================

class Test21NoLatency(unittest.TestCase):
    """Case 21: latency is a network_monitor metric, never set by the normalizer."""

    def test_latency_none(self):
        e = _n(_iot_payload())
        self.assertIsNone(e.network.latency)

    def test_latency_none_even_if_in_payload(self):
        p = _iot_payload()
        p["latency"] = 2.5
        e = _n(p)
        self.assertIsNone(e.network.latency)
        # Must end up in metadata instead
        self.assertEqual(e.metadata.get("latency"), 2.5)


# ===========================================================================
# TEST 22 — Absence of throughput
# ===========================================================================

class Test22NoThroughput(unittest.TestCase):
    """Case 22: throughput is a network_monitor metric, never set by the normalizer."""

    def test_throughput_none(self):
        e = _n(_iot_payload())
        self.assertIsNone(e.network.throughput)

    def test_throughput_none_even_if_in_payload(self):
        p = _iot_payload()
        p["throughput"] = 1024.0
        e = _n(p)
        self.assertIsNone(e.network.throughput)
        self.assertEqual(e.metadata.get("throughput"), 1024.0)


# ===========================================================================
# TEST 23 — Absence of all invented network metrics
# ===========================================================================

class Test23NoInventedNetworkMetrics(unittest.TestCase):
    """Case 23: packet_count, bytes_total, avg_interval and packet_size
    must never be populated by the normalizer."""

    def setUp(self):
        self.e = _n(_iot_payload())

    def test_no_packet_count(self):
        self.assertIsNone(self.e.network.packet_count)

    def test_no_bytes_total(self):
        self.assertIsNone(self.e.network.bytes_total)

    def test_no_avg_interval(self):
        self.assertIsNone(self.e.network.avg_interval)

    def test_no_packet_size(self):
        self.assertIsNone(self.e.network.packet_size)

    def test_all_metrics_none_together(self):
        n = self.e.network
        invented = [n.packet_count, n.bytes_total, n.avg_interval, n.packet_size,
                    n.latency, n.throughput, n.destination_port]
        self.assertTrue(all(v is None for v in invented),
                        f"Expected all None, got: {invented}")


# ===========================================================================
# Supplementary — metadata completeness
# ===========================================================================

class TestMetadataCompleteness(unittest.TestCase):
    """Unknown payload fields must reach metadata verbatim, no loss."""

    def test_unknown_string_field(self):
        e = _n({"device_id": "x", "type": "t", "timestamp": 0.0,
                "weird_field": "abc"})
        self.assertEqual(e.metadata.get("weird_field"), "abc")

    def test_nested_dict_in_metadata(self):
        e = _n({"device_id": "x", "type": "t", "timestamp": 0.0,
                "nested": {"a": 1, "b": 2}})
        self.assertEqual(e.metadata.get("nested"), {"a": 1, "b": 2})

    def test_consumed_keys_not_in_metadata(self):
        p = _iot_payload()
        e = _n(p)
        consumed = {"device_id", "type", "timestamp", "transport", "mqtt_topic",
                    "token", "value", "unit", "status", "people_count",
                    "latitude", "longitude", "ip_src", "mac_src", "port_src"}
        for key in consumed:
            with self.subTest(key=key):
                self.assertNotIn(key, e.metadata)


# ===========================================================================
# Supplementary — transport coercion and error handling
# ===========================================================================

class TestTransportCoercion(unittest.TestCase):
    """Transport accepted as enum or lowercase string; unknown raises."""

    def test_mqtt_string_accepted(self):
        e = _n({"device_id": "x", "type": "t", "timestamp": 0.0}, "mqtt")
        self.assertEqual(e.transport, Transport.MQTT)

    def test_http_string_accepted(self):
        e = _n({"device_id": "x", "type": "t", "timestamp": 0.0}, "http")
        self.assertEqual(e.transport, Transport.HTTP)

    def test_udp_string_accepted(self):
        e = _n({"device_id": "x", "type": "t", "timestamp": 0.0}, "udp")
        self.assertEqual(e.transport, Transport.UDP)

    def test_unknown_transport_raises_value_error(self):
        with self.assertRaises(ValueError):
            _n({"device_id": "x", "type": "t"}, "ftp")


# ===========================================================================
# Supplementary — event_id uniqueness
# ===========================================================================

class TestEventIdUniqueness(unittest.TestCase):
    """Each call must produce a distinct UUID4 event_id."""

    def test_two_calls_produce_different_event_ids(self):
        p = _iot_payload()
        e1 = _n(p)
        e2 = _n(p)
        self.assertNotEqual(e1.event_id, e2.event_id)

    def test_event_id_is_36_char_uuid(self):
        e = _n(_iot_payload())
        self.assertEqual(len(e.event_id), 36)
        parts = e.event_id.split("-")
        self.assertEqual(len(parts), 5)


if __name__ == "__main__":
    unittest.main()
